version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: ""
      DB_NAME: agustintaverna

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: agustintaverna
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init/:/docker-entrypoint-initdb.d/
volumes:
  db_data:
